import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// import ApolloUploadSetting from "@/commons/setttings/apollo-setting";
import dynamic from "next/dynamic";
import Layout from "@/commons/layout";
import ModalProvider from "@/commons/providers/modal/modal.provider";
import AuthProvider from "@/commons/providers/auth/auth.provider";
import AuthGuard from "@/commons/providers/auth/auth.guard";

const ApiHeaderProvider = dynamic(
  () => import("@/commons/setttings/apollo-setting"),
  { ssr: false }
);

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <head>
        <link
          rel="preload"
          href="/fonts/Pretendard-Regular.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <AuthProvider>
        <ApiHeaderProvider>
          <ModalProvider>
            <AuthGuard>
              <Layout>{children}</Layout>
            </AuthGuard>
          </ModalProvider>
        </ApiHeaderProvider>
       </AuthProvider>
      </body>
    </html>
  );
}
