import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// import ApolloUploadSetting from "@/commons/setttings/apollo-setting";
import Layout from "@/commons/layout";
import ApiHeaderProvider from "@/commons/setttings/apollo-setting";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <head>
        <link
          rel="preload"
          href="/fonts/Pretendard-Regular.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <ApiHeaderProvider>
        <Layout>{children}</Layout>
       </ApiHeaderProvider>
      </body>
    </html>
  );
}
